variables:
- name: GitHubPat
- name: PackageSourcePat

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: OneLocBuild@2
  inputs:
    locProj: 'LocProject.json'
    outDir: '$(Build.ArtifactStagingDirectory)'
    isCreatePrSelected: true
    repoType: 'gitHub'
    prSourceBranchPrefix: 'locfiles'
    isAutoCompletePrSelected: false
    isUseLfLineEndingsSelected: true
    gitHubPatVariable: '$(GitHubPat)'
    packageSourceAuth: patAuth
    patVariable: '$(PackageSourcePat)'